// Generated by CoffeeScript 1.6.3
(function() {
  var uniqueId;

  uniqueId = function(length) {
    var id;
    if (length == null) {
      length = 24;
    }
    id = "";
    while (id.length < length) {
      id += Math.random().toString(36).substr(2);
    }
    return id.substr(0, length);
  };

  module.exports = {
    uniqueId: uniqueId
  };

}).call(this);
