// Generated by CoffeeScript 1.6.3
(function() {
  var React;

  React = require('fora-react-sandbox');

  exports.renderForum = function*(data, context) {
    var component, membership, options, params, script, template, typeDefinition, _ref;
    typeDefinition = yield context.forum.getTypeDefinition();
    options = {};
    if (context.client.session) {
      options.loggedIn = true;
      membership = yield context.forum.getMembership(context.client.session.user.username);
      if (membership) {
        options.isMember = true;
        options.primaryPostType = "Article";
      }
    }
    template = yield context.extension.getTemplateModule(data.forumTemplate);
    component = template({
      posts: data.posts,
      forum: context.forum,
      postTemplate: data.postTemplate,
      options: options
    });
    if (component.type.componentInit && !component.__isInitted) {
      yield component.type.componentInit(component);
    }
    script = "<script> var page = new Fora.Views.Page( '/shared/extensions/" + typeDefinition.name + "/templates/" + data.forumTemplate + ".js', " + (JSON.stringify({
      posts: data.posts,
      forum: context.forum,
      postTemplate: data.postTemplate,
      options: options
    })) + " ); </script>";
    params = {
      html: "" + script + " " + (React.renderComponentToString(component)),
      pageName: "forum-item-page"
    };
    if (params.theme == null) {
      params.theme = context.client.network.theme;
    }
    if ((_ref = params.coverInfo) != null) {
      if (_ref["class"] == null) {
        _ref["class"] = "auto-cover";
      }
    }
    if (context.client.session) {
      if (params._session == null) {
        params._session = context.client.session.user;
      }
    }
    return yield context.client.render("page", params);
  };

  exports.renderPost = function*(data, context) {
    var author, component, options, params, script, template, typeDefinition, _ref;
    typeDefinition = yield context.forum.getTypeDefinition();
    author = yield data.post.getAuthor();
    options = {};
    if (context.client.session) {
      options.loggedIn = true;
    }
    template = yield context.extension.getTemplateModule(data.forumTemplate);
    component = template({
      post: data.post,
      forum: context.forum,
      author: author,
      postTemplate: data.postTemplate
    });
    if (component.type.componentInit && !component.__isInitted) {
      yield component.type.componentInit(component);
    }
    script = "<script> var page = new Fora.Views.Page( '/shared/extensions/" + typeDefinition.name + "/templates/" + data.forumTemplate + ".js', " + (JSON.stringify({
      post: data.post,
      forum: context.forum,
      author: author,
      postTemplate: data.postTemplate
    })) + " ); </script>";
    params = {
      html: "" + script + " " + (React.renderComponentToString(component)),
      pageName: "forum-item-page"
    };
    if (params.theme == null) {
      params.theme = context.client.network.theme;
    }
    if ((_ref = params.coverInfo) != null) {
      if (_ref["class"] == null) {
        _ref["class"] = "auto-cover";
      }
    }
    if (context.client.session) {
      if (params._session == null) {
        params._session = context.client.session.user;
      }
    }
    return yield context.client.render("page", params);
  };

}).call(this);
