// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    Cover: require('./controls/cover'),
    Page: require('./controls/page'),
    Content: require('./controls/content'),
    PostEditor: require('./controls/posteditor'),
    helpers: require('./helpers')
  };

}).call(this);
