// Generated by CoffeeScript 1.6.3
(function() {
  var ForaDbModel, ForaModel, ForaTypeUtils, odm, typeUtils,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  odm = require('fora-models');

  ForaTypeUtils = require('./foratypeutils');

  typeUtils = new ForaTypeUtils();

  ForaModel = (function(_super) {
    __extends(ForaModel, _super);

    function ForaModel() {
      return ForaModel.__super__.constructor.apply(this, arguments);
    }

    ForaModel.getTypeUtils = function() {
      return typeUtils;
    };

    return ForaModel;

  })(odm.BaseModel);

  ForaDbModel = (function(_super) {
    __extends(ForaDbModel, _super);

    function ForaDbModel() {
      this.initialize = __bind(this.initialize, this);
      return ForaDbModel.__super__.constructor.apply(this, arguments);
    }

    ForaDbModel.getTypeUtils = function() {
      return typeUtils;
    };

    ForaDbModel.prototype.initialize = function*() {
      return this["typeDefinition"] = yield this.getTypeDefinition();
    };

    return ForaDbModel;

  })(odm.DatabaseModel);

  exports.ForaModel = ForaModel;

  exports.ForaDbModel = ForaDbModel;

}).call(this);
