// Generated by CoffeeScript 1.6.2
(function() {
  var c, compressor, opt;

  compressor = require('node-minify');

  if (process.argv.length > 2) {
    opt = process.argv[2];
    console.log("Options: " + process.argv[2]);
  }

  if (opt !== '--debug' && opt !== '--trace') {
    console.log("Minifying CSS...");
    c = new compressor.minify({
      type: 'sqwish',
      buffer: 1000 * 1024,
      tempPath: 'tmp',
      fileIn: ['app/www/lib/font-awesome/css/font-awesome.css', 'app/www/css/HINT.css', 'app/www/css/toggle-switch.css'],
      fileOut: 'app/www/js/lib.css',
      callback: function(err) {
        if (err) {
          return console.log(err);
        } else {
          return console.log('Created lib.css');
        }
      }
    });
    c = new compressor.minify({
      type: 'sqwish',
      buffer: 1000 * 1024,
      tempPath: 'tmp',
      fileIn: ['app/www/css/main.css'],
      fileOut: 'app/www/js/fora.css',
      callback: function(err) {
        if (err) {
          return console.log(err);
        } else {
          return console.log('Created fora.css');
        }
      }
    });
    console.log("Minifying JS...");
    c = new compressor.minify({
      type: 'no-compress',
      buffer: 1000 * 1024,
      tempPath: 'tmp',
      fileIn: ['app/www/js/lib/jquery-min.js', 'app/www/js/lib/angular-min.js'],
      fileOut: 'app/www/js/lib-base.js',
      callback: function(err) {
        if (err) {
          return console.log(err);
        } else {
          return console.log('Created lib-base.js');
        }
      }
    });
    c = new compressor.minify({
      type: 'uglifyjs',
      buffer: 1000 * 1024,
      tempPath: 'tmp',
      fileIn: ['app/www/js/lib/jquery-cookie.js', 'app/www/lib/bangjs/reMarked.js', 'app/www/lib/bangjs/jquery-drags.js', 'app/www/lib/bangjs/bangjs.js', 'app/www/lib/bangjs/bangjs-toolbar.js'],
      fileOut: 'app/www/js/lib.js',
      callback: function(err) {
        if (err) {
          return console.log(err);
        } else {
          return console.log('Created lib.js');
        }
      }
    });
    c = new compressor.minify({
      type: 'uglifyjs',
      buffer: 1000 * 1024,
      tempPath: 'tmp',
      fileIn: [],
      fileOut: 'app/www/js/fora.js',
      callback: function(err) {
        if (err) {
          return console.log(err);
        } else {
          return console.log('Created fora.js');
        }
      }
    });
  } else {
    console.log("Skipped minify in debug mode.");
  }

}).call(this);
