isUserDefinedType = (type) ->
    ['string', 'number', 'boolean', 'object', 'array', ''].indexOf(type) is -1   
    

getTypeDefinition = (def) ->
    #Convert short hands to full definitions.
    #eg: 'string' means { type: 'string', required: true }
    if typeof(def) isnt "object"
        fieldDef = {
            type: def,
            required: true
        }
    else 
        fieldDef = def

    if fieldDef.autoGenerated and (fieldDef.event is 'created' or fieldDef.event is 'updated')
        fieldDef.type = 'number'
        fieldDef.required = true

    fieldDef.required ?= true
    fieldDef.type ?= ''
        
    fieldDef._type = fieldDef.type ? fieldDef.getType()
    if fieldDef._type is 'array'
        fieldDef._contentType = fieldDef.contentType ? fieldDef.getContentType()
    fieldDef    
    
    
exports.isUserDefinedType = isUserDefinedType
exports.getTypeDefinition = getTypeDefinition

