DatabaseAppModel = require('./appmodels').DatabaseAppModel

class Attachment extends DatabaseAppModel

    @describeModel: ->
        {
            type: @,
            collection: 'tokens',
            fields: {
                type: 'string',
                key: 'string',
                value: '',
                createdAt: { autoGenerated: true, event: 'created' },
                updatedAt: { autoGenerated: true, event: 'updated' }
            },
            logging: {
                isLogged: false,
            }
        }
    
    
exports.Attachment = Attachment
