BaseModel = require('./basemodel').BaseModel

class Comment extends BaseModel

    @describeModel: ->
        {
            type: @,
            collection: 'comments',
            fields: {
                forum: 'string',
                postid: 'string',
                data: 'object',
                createdBy: { type: @getModels().User.Summary },
                createdAt: { autoGenerated: true, event: 'created' },
                updatedAt: { autoGenerated: true, event: 'updated' }
            },        
            logging: {
                isLogged: true,
                onInsert: 'NEW_COMMENT'
            },
            validateMultiRecordOperationParams: (params) ->            
                params.postid
        }
        
    
exports.Comment = Comment
