DatabaseModel = require('../common/data/databasemodel').DatabaseModel
models = require('./')

class Comment extends DatabaseModel

    @describeModel: {
        type: @,
        collection: 'comments',
        fields: {
            forum: 'string',
            postid: 'string',
            data: 'object',
            createdBy: { type: models.User.Summary },
            createdAt: { autoGenerated: true, event: 'created' },
            updatedAt: { autoGenerated: true, event: 'updated' }
        },        
        logging: {
            onInsert: 'NEW_COMMENT'
        },
        validateMultiRecordOperationParams: (params) ->            
            params.postid
    }
        
    
exports.Comment = Comment
