AppError = require('../common/apperror').AppError
BaseModel = require('./basemodel').BaseModel
User = require('./user').User

class Comment extends BaseModel

    @_meta: {
        type: Comment,
        collection: 'comments',
        fields: {
            network: 'string',
            forum: 'string',
            itemid: 'string',
            data: 'object',
            createdBy: { type: User.Summary, validate: -> @createdBy.validate() },
            createdAt: { autoGenerated: true, event: 'created' },
            updatedAt: { autoGenerated: true, event: 'updated' }
        },        
        logging: {
            isLogged: true,
            onInsert: 'NEW_COMMENT'
        },
        validateMultiRecordOperationParams: (params) ->            
            params.postid
    }
        
    
    save: (context, cb) =>
        super context, cb
        

        
    
exports.Comment = Comment
