AppError = require('../common/apperror').AppError
BaseModel = require('./basemodel').BaseModel

class Credentials extends BaseModel
    
    @describeModel: ->
        {
            type: Credentials,
            collection: 'credentials',
            fields: {
                userid: 'string',
                username: 'string',
                token: 'string',
                builtin: { required: false, validate: -> if @method is 'PBKDF2' and @builtin.hash and @builtin.salt then true else false }
                twitter: { required: false, validate: -> if @twitter.username and @twitter.accessToken then true else false }
                facebook: { required: false, validate: -> if @facebook.username and @facebook.accessToken then true else false }
                createdAt: { autoGenerated: true, event: 'created' },
                updatedAt: { autoGenerated: true, event: 'updated' }
            },
            validate: (fields) ->
                if not @builtin and not @twitter and not @facebook
                    ['At least one credential must me specified.']
            logging: {
                isLogged: false
            }
        }    



exports.Credentials = Credentials
