DatabaseModel = require('../common/data/databasemodel').DatabaseModel

class DataType extends DatabaseModel
    
    @describeType: {
        type: @,
        collection: 'datatypes',
        fields: {
            createdAt: { autoGenerated: true, event: 'created' },
            updatedAt: { autoGenerated: true, event: 'updated' }
        },
    }

            
exports.DataType = DataType
