DatabaseAppModel = require('./appmodels').DatabaseAppModel

class ExtendedField extends DatabaseAppModel

    @describeModel: ->
        {
            type: @,
            collection: 'extendedfields',
            fields: {
                type: 'string',
                key: 'string',
                value: '',
                createdAt: { autoGenerated: true, event: 'created' },
                updatedAt: { autoGenerated: true, event: 'updated' }
            },
        }
    
    
exports.ExtendedField = ExtendedField
