BaseModel = require('./basemodel').BaseModel
AppError = require('../common/apperror').AppError

class ItemView extends BaseModel

    @_meta: {
        type: ItemView,
        collection: 'itemviews',
        fields: {
            network: 'string',
            forum: 'string',
            itemid: 'string',
            type: 'string',
            data: 'object',
            meta: { type: 'array', contents: 'string' },
            createdBy: { type: @_models.User.Summary },
            publishedAt: { type: 'number', validate: -> if @publishedAt and isNaN(@publishedAt) then ['PublishedAt must be a number.'] },
            state: { type: 'string', validate: -> if ['new', 'draft', 'published'].indexOf(@) is -1 then ['State should be one of new, draft or published.'] },
            createdAt: { autoGenerated: true, event: 'created' },
            updatedAt: { autoGenerated: true, event: 'updated' }
        },
        logging: {
            isLogged: false,
        }
    }



    @search: (criteria, settings, context, cb) =>
        limit = @getLimit settings.limit, 100, 1000
                
        params = {}
        for k, v of criteria
            params[k] = v
        
        ItemView.find params, ((cursor) -> cursor.sort(settings.sort).limit limit), context, cb     
        
            

    constructor: (params) ->
        @meta ?= []
        super
        
        

    save: (context, cb) =>            
        super
            
            

    validate: =>
        errors = super().errors

        if not @network or typeof @network isnt 'string'
            errors.push 'Invalid network.'      
                    
        if not @forum
            errors.push 'Invalid forum.'

        if not @data
            errors.push 'data missing.'
            
        for item in @meta
            if typeof item isnt 'string'
                errors.push "Invalid item(#{item}) in meta."

        if not @type or ['featured', 'post'].indexOf(@type) is -1
            errors.push "Invalid type."

        _errors = ItemView._models.User.validateSummary(@createdBy)
        if _errors.length            
            errors.push 'Invalid createdBy.'
            errors = errors.concat _errors
                    
        if @publishedAt and isNaN(@publishedAt)
            errors.push 'PublishedAt must be a number.'

        if not @state
            errors.push 'Invalid state.'

        { isValid: errors.length is 0, errors }
    
    
    
exports.ItemView = ItemView
