DatabaseAppModel = require('./appmodels').DatabaseAppModel
Q = require('../common/q')

class Membership extends DatabaseAppModel
    
    @describeModel: ->
        {
            type: @,
            collection: 'memberships',
            fields: {
                userid: 'string',
                forumid: 'string',
                roles: { type: 'array', contents: 'string' }
                createdAt: { autoGenerated: true, event: 'created' },
                updatedAt: { autoGenerated: true, event: 'updated' }
            },
        }    


exports.Membership = Membership
