BaseModel = require('./basemodel').BaseModel
AppError = require('../common/apperror').AppError

class Session extends BaseModel

    
    @_meta: {
        type: Session,
        collection: 'sessions',
        fields: {
            network: 'string',
            passkey: 'string',
            accessToken: 'string',
            userid: 'string',
            createdAt: { autoGenerated: true, event: 'created' },
            updatedAt: { autoGenerated: true, event: 'updated' }
        },
        logging: {
            isLogged: false
        }
    }    



exports.Session = Session
