thunkify = require 'thunkify'
ForaDbModel = require('./foramodel').ForaDbModel
models = require('./')

###
    A session token starts life as a credential token.
    A credential token can be converted into a user-session token.
###
class Session extends ForaDbModel
    
    @typeDefinition: {
        name: 'session',
        collection: 'sessions',
        schema: {
            type: 'object',        
            properties: {
                credentialId: { type: 'string' }
                userId: { type: 'string' },
                token: { type: 'string' },
                user: { $ref: 'user-summary' }
            },
            required: ['credentialId', 'token']
        },
        autoGenerated: {
            createdAt: { event: 'created' },
            updatedAt: { event: 'updated' }
        },
        indexes: [
            { 'userId': 1, 'token': 1 },
        ]
    }
    
    
exports.Session = Session
