thunkify = require 'thunkify'
ForaDbModel = require('./foramodel').ForaDbModel
models = require('./')


class Session extends ForaDbModel
    
    @typeDefinition: {
        name: 'session',
        collection: 'sessions',
        schema: {
            type: 'object',        
            properties: {
                userId: { type: 'string' },
                token: { type: 'string' },
                user: { $ref: 'user-summary' }
            },
            required: ['userId', 'token', 'user']
        },
        autoGenerated: {
            createdAt: { event: 'created' },
            updatedAt: { event: 'updated' }
        },
        indexes: [
            { 'userId': 1, 'token': 1 },
        ]
    }
    
    
exports.Session = Session
