DatabaseModel = require('../common/data/databasemodel').DatabaseModel
models = require('./')

class Token extends DatabaseModel

    @describeType: {
        type: @,
        collection: 'tokens',
        fields: {
            type: 'string',
            key: 'string',
            value: '',
            createdAt: { autoGenerated: true, event: 'created' },
            updatedAt: { autoGenerated: true, event: 'updated' }
        },
    }
        
    
exports.Token = Token
