BaseModel = require('./basemodel').BaseModel
AppError = require('../common/apperror').AppError

class Token extends BaseModel

    @_meta: {
        type: Token,
        collection: 'tokens',
        fields: {
            network: 'string',
            type: 'string',
            key: 'string',
            value: 'string',
            createdAt: { autoGenerated: true, event: 'created' },
            updatedAt: { autoGenerated: true, event: 'updated' }
        },
        logging: {
            isLogged: false,
        }
    }
    

    
exports.Token = Token
