DatabaseModel = require('../common/data/databasemodel').DatabaseModel
models = require('./')

class TypeDefinition extends DatabaseModel
    
    @describeType: {
        type: @,
        collection: 'typedefinitions',
        fields: {
            name: 'string',
            value: { 
                type: 'object',
                fields: {
                    type: 'string',
                    collection: 'string',
                    fields: { type: 'array', contents: 'object' }
                }
            },
            createdBy: { type: models.User.Summary },
            createdAt: { autoGenerated: true, event: 'created' },
            updatedAt: { autoGenerated: true, event: 'updated' }
        },
    }

            
exports.TypeDefinition = TypeDefinition
