ForaDbModel = require('./foramodel').ForaDbModel
models = require('./')

class UserInfo extends ForaDbModel

    @describeType: {
        type: @,
        collection: 'userinfo',
        fields: {
            userid: 'string',
            subscriptions: { type: 'array', contents: { type: models.Collection.Summary } },
            following: { type: 'array', contents: { type: models.User.Summary } },
            lastMessageAccessTime: { type: 'number', required: false },
            createdAt: { autoGenerated: true, event: 'created' },
            updatedAt: { autoGenerated: true, event: 'updated' }
        },
        logging: {
            onInsert: 'NEW_USER'
        }
    }

    
    constructor: (params) ->
        @subscriptions ?= []
        @following ?= []
        super
        


exports.UserInfo = UserInfo
