ForaDbModel = require('./foramodel').ForaDbModel
models = require('./')

class UserInfo extends ForaDbModel

    @typeDefinition: {
        type: @,
        alias: "UserInfo",
        collection: 'userinfo',
        fields: {
            userid: 'string',
            subscriptions: { type: 'array', contents: { type: "Collection.Summary" } },
            following: { type: 'array', contents: { type: "User.Summary" } },
            lastMessageAccessTime: 'number !required',
            createdAt: { autoGenerated: true, event: 'created' },
            updatedAt: { autoGenerated: true, event: 'updated' }
        },
        logging: {
            onInsert: 'NEW_USER'
        }
    }

    
    constructor: (params) ->
        @subscriptions ?= []
        @following ?= []
        super
        


exports.UserInfo = UserInfo
