ForaModel = require('./foramodel').ForaModel
ForaDbModel = require('./foramodel').ForaDbModel

class AppBase extends ForaDbModel

    class Settings extends ForaModel
        @typeDefinition: {
            name: "app-settings",
            schema: {
                type: 'object',
                properties: {
                    commentsEnabled: { type: 'boolean' },
                    commentsOpened: { type: 'boolean' }
                }
            }
        }

    @Settings: Settings

    class Summary extends ForaModel
        @typeDefinition: {
            name: "app-summary",
            schema: {
                type: 'object',
                properties: {
                    id: { type: 'string' },
                    network: { type: 'string' },
                    name: { type: 'string' },
                    stub: { type: 'string' },
                    createdBy: { $ref: "user-summary" }
                },
                required: ['id', 'network', 'name', 'stub', 'createdBy']
            }
        }

    @Summary: Summary

    class Stats extends ForaModel
        @typeDefinition: {
            name: "app-stats",
            schema: {
                type: 'object',
                properties: {
                    records: { type: 'number' },
                    members: { type: 'number' },
                    lastRecord: { type: 'number' }
                }
                required: ['records', 'members', 'lastRecord']
            }
        }

    @Stats: Stats

    @childModels: { Stats, Summary, Settings }

    @typeDefinition: -> {
        name: 'app',
        collection: 'apps',
        schema: {
            type: 'object',
            properties: {
                type: { type: 'string' },
                network: { type: 'string' },
                name: { type: 'string' },
                description: { type: 'string' },
                stub: { type: 'string' },
                access: { type: 'string', enum: ['public', 'protected', 'private'] },
                createdById: { type: 'string' }
                createdBy: { $ref: 'user-summary' },
                settings: { $ref: 'app-settings' },
                cover: { $ref: 'cover' },
                theme: { type: 'string' },
                cache: {
                    type: 'object',
                    properties: {
                        records: {
                            type: 'array',
                            items: {
                                type: 'object',
                                properties: {
                                    image: { type: 'string' },
                                    title: { type: 'string' },
                                    createdBy: { $ref: 'user-summary' }
                                    id: { type: 'string' },
                                    stub: { type: 'string' }
                                },
                                required: ['title', 'createdBy', 'id', 'stub']
                            }
                        }
                    }
                    required: ['records']
                }
                stats: { $ref: 'app-stats' },
            }
            required: ['type', 'network', 'name', 'description', 'stub', 'access', 'createdById', 'createdBy', 'cache', 'stats']
        },
        indexes: [
            { 'createdById': 1, 'network': 1 },
            {'stub': 1, 'network': 1 }
        ],
        autoGenerated: {
            createdAt: { event: 'created' },
            updatedAt: { event: 'updated' }
        },
        links: {
            createdBy: { type: 'user-summary', key: 'createdById' }
            records: { type: 'record', field: 'appId' },
            info: { type: 'app-info', field: 'appId' }
        },
        logging: {
                onInsert: 'NEW_FORUM'
        }
    }


exports.AppBase = AppBase
