(function() {
	"use strict";

	var __hasProp = {}.hasOwnProperty,
		__extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } };

	var ForaModel = require('./foramodel').ForaModel;
	var ForaDbModel = require('./foramodel').ForaDbModel;

	var AppBase = function() {
		ForaDbModel.apply(this, arguments);
	};

	AppBase.prototype = Object.create(ForaDbModel.prototype);
	AppBase.prototype.constructor = AppBase;

	__extends(AppBase, ForaDbModel);


	//AppSettings
	var AppSettings = function() {
		ForaModel.apply(this, arguments);
	};

	AppSettings.prototype = Object.create(ForaModel.prototype);
	AppSettings.prototype.constructor = AppSettings;

	__extends(AppSettings, ForaModel);

	AppSettings.typeDefinition = {
		name: "app-settings",
		schema: {
			type: 'object',
			properties: {
				commentsEnabled: { type: 'boolean' },
				commentsOpened: { type: 'boolean' }
			}
		}
	};


	//AppSummary
	var AppSummary = function() {
		ForaModel.apply(this, arguments);
	};

	AppSummary.prototype = Object.create(ForaModel.prototype);
	AppSummary.prototype.constructor = AppSummary;

	__extends(AppSummary, ForaModel);

	AppSummary.typeDefinition = {
		name: "app-summary",
		schema: {
			type: 'object',
			properties: {
				id: {
					type: 'string'
				},
				name: {
					type: 'string'
				},
				stub: {
					type: 'string'
				},
				createdBy: {
					$ref: "user-summary"
				}
			},
			required: ['id', 'name', 'stub', 'createdBy']
		}
	};


	//AppSummary
	var AppStats = function() {
		ForaModel.apply(this, arguments);
	};

	AppStats.prototype = Object.create(ForaModel.prototype);
	AppStats.prototype.constructor = AppStats;

	__extends(AppStats, ForaModel);


	AppStats.typeDefinition = {
		name: "app-stats",
		schema: {
			type: 'object',
			properties: {
				records: {
					type: 'number'
				},
				members: {
					type: 'number'
				},
				lastRecord: {
					type: 'number'
				}
			},
			required: ['records', 'members', 'lastRecord']
		}
	};


	AppBase.typeDefinition = {
		name: 'app',
		collection: 'apps',
		schema: {
			type: 'object',
			properties: {
				type: { type: 'string' },
				name: { type: 'string' },
				description: { type: 'string' },
				stub: { type: 'string' },
				access: {
					type: 'string',
					"enum": ['public', 'protected', 'private']
				},
				createdById: { type: 'string' },
				createdBy: { $ref: 'user-summary' },
				settings: { $ref: 'app-settings' },
				cover: { $ref: 'cover' },
				theme: { type: 'string' },
				cache: {
					type: 'object',
					properties: {
						records: {
							type: 'array',
							items: {
								type: 'object',
								properties: {
									image: { type: 'string' },
									title: { type: 'string' },
									createdBy: { $ref: 'user-summary' },
									id: { type: 'string' },
									stub: { type: 'string' }
								},
								required: ['title', 'createdBy', 'id', 'stub']
							}
						}
					},
					required: ['records']
				},
				stats: { $ref: 'app-stats' }
			},
			required: ['type', 'name', 'description', 'stub', 'access', 'createdById', 'createdBy', 'cache', 'stats']
		},
		indexes: [ {
				'createdById': 1,
			}, {
				'stub': 1
			}
		],
		autoGenerated: {
			createdAt: { event: 'created' },
			updatedAt: { event: 'updated' }
		},
		links: {
			createdBy: { type: 'user-summary', key: 'createdById' },
			records: { type: 'record', field: 'appId' },
			info: { Type: 'app-info', field: 'appId' }
		},
		logging: {
			onInsert: 'NEW_FORUM'
		}
	};


	exports.AppBase = AppBase;
	exports.AppStats = AppStats;
	exports.AppSummary = AppSummary;
	exports.AppSettings = AppSettings;


})();
