ForaDbModel = require('./foramodel').ForaDbModel
models = require('./')

class Membership extends ForaDbModel
    
    @typeDefinition: {
        name: "membership",
        collection: 'memberships',
        schema: {
            type: 'object',        
            properties: {
                userId: { type: 'string' }
                user: { $ref: 'user-summary'},
                appId: { type: 'string' },
                app: { $ref: 'app-summary' },
                roles: { type: 'array', items: { type: 'string' } },
            },
            required: ['userId', 'user', 'appId', 'app', 'roles'],
        },
        links: {
            user: { type: 'user', key: 'userId' },
            app: { type: 'app', key: 'appId' }
        },
        autoGenerated: {
            createdAt: { event: 'created' },
            updatedAt: { event: 'updated' }
        },
    }    


exports.Membership = Membership
