// Generated by CoffeeScript 1.6.2
(function() {
  var AppError, Article, Models, async, mdparser, utils, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  async = require('../common/async');

  utils = require('../common/utils');

  AppError = require('../common/apperror').AppError;

  Models = require('./');

  mdparser = require('../common/markdownutil').marked;

  Article = (function(_super) {
    __extends(Article, _super);

    function Article() {
      _ref = Article.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Article._meta = (function() {
      var meta;

      meta = {
        collection: 'articles',
        fields: {
          stub: {
            type: 'string',
            required: false
          },
          state: {
            type: 'string',
            validate: function() {
              return ['draft', 'published'].indexOf(this.state);
            }
          },
          title: 'string',
          summary: {
            type: 'string',
            required: 'false'
          },
          publishedAt: {
            type: 'number',
            validate: function() {
              if (this.state === 'published' && !this.publishedAt) {
                return 'Published post must have a publishedAt field.';
              }
            }
          }
        }
      };
      return utils.extend(meta, utils.clone(Post._meta));
    })();

    return Article;

  })(Models.Post);

  exports.Article = Article;

}).call(this);
