// Generated by CoffeeScript 1.6.2
(function() {
  var AppError, BaseModel, Message, moment,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BaseModel = require('./basemodel').BaseModel;

  AppError = require('../common/apperror').AppError;

  moment = require('../common/moment');

  Message = (function(_super) {
    __extends(Message, _super);

    /*
        Fields
            - network (string)        
            - userid (string)
            - type (string; global-notification, user-notification)
            - reason (string; new-user, new-post etc)
            - data (object, depends on reason). We don't validate this.
    */


    Message._meta = {
      type: Message,
      collection: 'messages',
      autoInsertedFields: {
        created: 'createdAt',
        updated: 'timestamp'
      },
      logging: {
        isLogged: true,
        onInsert: 'NEW_MESSAGE'
      }
    };

    function Message(params) {
      this.validate = __bind(this.validate, this);
      this.format = __bind(this.format, this);
      this.save = __bind(this.save, this);
      var _ref;

      if ((_ref = this.priority) == null) {
        this.priority = 'normal';
      }
      Message.__super__.constructor.apply(this, arguments);
    }

    Message.prototype.save = function(context, cb) {
      return Message.__super__.save.apply(this, arguments);
    };

    Message.prototype.format = function(_format) {
      var error, user;

      try {
        switch (_format) {
          case 'timeline':
            switch (this.reason) {
              case 'new-collection':
                user = this.data.collection.createdBy;
                return {
                  subject: {
                    thumbnail: user.thumbnail,
                    name: user.name,
                    link: user.domain === 'tw' ? "/@" + user.username : "/" + user.domain + "/" + user.username
                  },
                  verb: "added a new collection",
                  object: {
                    thumbnail: this.data.collection.icon,
                    name: this.data.collection.name,
                    link: "/" + this.data.collection.stub
                  },
                  time: moment(this.timestamp).from(Date.now())
                };
              case 'published-post':
                user = this.data.post.createdBy;
                return {
                  subject: {
                    thumbnail: user.thumbnail,
                    name: user.name,
                    link: user.domain === 'tw' ? "/@" + user.username : "/" + user.domain + "/" + user.username
                  },
                  verb: "published",
                  object: {
                    name: this.data.post.title,
                    link: "/" + this.data.post.collections[0].stub + "/" + this.data.post.uid
                  },
                  time: moment(this.timestamp).from(Date.now())
                };
            }
        }
      } catch (_error) {
        error = _error;
        return '';
      }
    };

    Message.prototype.validate = function() {
      var errors, _errors;

      errors = Message.__super__.validate.call(this).errors;
      if (!this.network || typeof this.network !== 'string') {
        errors.push('Invalid network.');
      }
      if (this.userid == null) {
        errors.push('Invalid userid.');
      }
      if (!this.type) {
        errors.push('Invalid type.');
      }
      if (this.type === 'user-notification') {
        _errors = Message._models.User.validateSummary(this.to);
        if (_errors.length) {
          errors.push('Invalid to.');
          errors.concat(_errors);
        }
        _errors = Message._models.User.validateSummary(this.from);
        if (_errors.length) {
          errors.push('Invalid from.');
          errors.concat(_errors);
        }
      }
      return {
        isValid: errors.length === 0,
        errors: errors
      };
    };

    return Message;

  })(BaseModel);

  exports.Message = Message;

}).call(this);
