// Generated by CoffeeScript 1.6.3
(function() {
  var AppError, BaseModel, UserInfo,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  AppError = require('../common/apperror').AppError;

  BaseModel = require('./basemodel').BaseModel;

  UserInfo = (function(_super) {
    __extends(UserInfo, _super);

    UserInfo.describeModel = function() {
      return {
        type: UserInfo,
        collection: 'userinfo',
        fields: {
          userid: 'string',
          subscriptions: {
            type: 'array',
            contents: this.getModels().Forum.Summary,
            validate: function() {
              var item, _i, _len, _ref, _results;
              _ref = this.subscriptions;
              _results = [];
              for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                item = _ref[_i];
                _results.push(item.validate());
              }
              return _results;
            }
          },
          following: {
            type: 'array',
            contents: this.getModels().User.Summary,
            validate: function() {
              var item, _i, _len, _ref, _results;
              _ref = this.following;
              _results = [];
              for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                item = _ref[_i];
                _results.push(item.validate());
              }
              return _results;
            }
          },
          lastMessageAccessTime: {
            type: 'number',
            required: false
          },
          createdAt: {
            autoGenerated: true,
            event: 'created'
          },
          updatedAt: {
            autoGenerated: true,
            event: 'updated'
          }
        },
        logging: {
          isLogged: false,
          onInsert: 'NEW_USERINFO'
        }
      };
    };

    function UserInfo(params) {
      if (this.subscriptions == null) {
        this.subscriptions = [];
      }
      if (this.following == null) {
        this.following = [];
      }
      UserInfo.__super__.constructor.apply(this, arguments);
    }

    return UserInfo;

  })(BaseModel);

  exports.UserInfo = UserInfo;

}).call(this);
