// Generated by CoffeeScript 1.6.2
(function() {
  var marked;

  marked = require('marked');

  marked.setOptions({
    gfm: true,
    tables: true,
    breaks: false,
    pedantic: false,
    sanitize: false,
    smartLists: true,
    langPrefix: 'language-',
    highlight: function(code, lang) {
      if (lang === 'js') {
        return highlighter.javascript(code);
      }
      return code;
    }
  });

  exports.marked = marked;

}).call(this);
