// Generated by CoffeeScript 1.6.2
(function() {
  var k, modules, v;

  modules = {
    sessions: 'Sessions',
    forums: 'Forums',
    articles: 'Articles'
  };

  for (k in modules) {
    v = modules[k];
    exports[v] = require("./" + k)[v];
  }

}).call(this);
