// Generated by CoffeeScript 1.6.2
(function() {
  var anupk7, articles, believeYouCanChange, cherishMistakes, computers, confrontReality, darkKnight, earlyMornings, ebin, fixTheMachine, forums, guzzlers, itsMyLife, jeswin, leanIntoThePain, lookAtYourselfObjectively, makingStuff, movies, optimalBiases, poetry, rawNerve, streetFood, takeAStepBack, theGreatMasters, travel, tributeToAaron, users;

  tributeToAaron = {
    username: 'aaronsw',
    name: 'Aaron Swartz Tribute',
    location: 'Brooklyn, NYC',
    domain: 'users',
    domainid: 'aaronsw',
    email: 'me@aaronsw.com',
    picture: 'http://i1.sndcdn.com/artworks-000039832777-og5thh-crop.jpg?86be403',
    thumbnail: 'http://i1.sndcdn.com/artworks-000039832777-og5thh-crop.jpg?86be403'
  };

  jeswin = {
    username: 'jeswin',
    name: 'Jeswin',
    location: 'Bangalore, India',
    domain: 'users',
    domainid: 'jeswin',
    email: 'jeswinpk@agilehead.com',
    picture: 'https://dge9rmgqjs8m1.cloudfront.net/global/6de4c55ef2bc00dfc5c521507ef2a42e6510b7a50114395442e00553d379b851cff71cf95e2bf3cb6a3b3bc3fbdb504c12c4d71779b248f5409e350ddf47eb54f9f7f8d7d4b1eafe8a95cd7825b9c9da/avatar.96.gif?r=3',
    thumbnail: 'https://dge9rmgqjs8m1.cloudfront.net/global/6de4c55ef2bc00dfc5c521507ef2a42e6510b7a50114395442e00553d379b851cff71cf95e2bf3cb6a3b3bc3fbdb504c12c4d71779b248f5409e350ddf47eb54f9f7f8d7d4b1eafe8a95cd7825b9c9da/avatar.40.gif?r=3'
  };

  ebin = {
    username: 'ebin',
    name: 'Ebin John',
    location: 'Bangalore, India',
    domain: 'users',
    domainid: 'ebin',
    email: 'ebin.john@outlook.com',
    picture: 'https://lh4.googleusercontent.com/-SyoIfkRItqE/AAAAAAAAAAI/AAAAAAAAAw0/nxHk4Nqrpm8/s120-c/photo.jpg',
    thumbnail: 'https://lh4.googleusercontent.com/-SyoIfkRItqE/AAAAAAAAAAI/AAAAAAAAAw0/nxHk4Nqrpm8/s120-c/photo.jpg'
  };

  anupk7 = {
    username: 'anupk7',
    name: 'Anup Kesavan',
    location: 'Bangalore, India',
    domain: 'users',
    domainid: 'anupk7',
    email: 'anupk7@gmail.com',
    picture: 'http://m.c.lnkd.licdn.com/mpr/pub/image-JLwJ9fTJBTv3Ur9xL18X4Ph00ExD3ZziHjwE4tuK0R2-tCRVJLwEuu6J0rLm3Zhhd9sr/anup-kesavan-ponnarassery.jpg',
    thumbnail: 'http://m.c.lnkd.licdn.com/mpr/pub/image-JLwJ9fTJBTv3Ur9xL18X4Ph00ExD3ZziHjwE4tuK0R2-tCRVJLwEuu6J0rLm3Zhhd9sr/anup-kesavan-ponnarassery.jpg'
  };

  users = [tributeToAaron, jeswin, ebin, anupk7];

  poetry = {
    name: 'Poetry',
    description: 'Selected Poetry from around the world.',
    icon: 'https://twimg0-a.akamaihd.net/profile_images/2926658252/11c12e7e2f293194c95c6a5ba3f4d707.jpeg',
    iconThumbnail: 'https://twimg0-a.akamaihd.net/profile_images/2926658252/11c12e7e2f293194c95c6a5ba3f4d707.jpeg',
    permission: 'public',
    type: 'post',
    category: 'literature',
    _createdBy: 'aaronsw'
  };

  movies = {
    name: 'Modern Cinema',
    description: 'Movies that won\'t make any sense. Not now, not ever.',
    icon: 'http://canasiantimes.com/wp-content/uploads/2013/01/TKL180cm.jpg',
    iconThumbnail: 'http://canasiantimes.com/wp-content/uploads/2013/01/TKL180cm.jpg',
    cover: 'http://theredlist.fr/media/database/muses/couples/hollywood/paulette_godard_charlie_chaplin/017_paulette_godard_charlie_chaplin_theredlist.jpg',
    permission: 'public',
    type: 'post',
    category: 'movies',
    _createdBy: 'aaronsw'
  };

  rawNerve = {
    name: 'Raw Nerve',
    description: 'This is a series of pieces on getting better at life.',
    icon: 'http://images.scroll.com.tr/2013/01/Aaron-Swartz.jpg',
    iconThumbnail: 'http://images.scroll.com.tr/2013/01/Aaron-Swartz.jpg',
    cover: 'http://farm9.staticflickr.com/8384/8462699292_1f68a9cd3e_b.jpg',
    permission: 'public',
    type: 'post',
    category: 'life',
    _createdBy: 'aaronsw'
  };

  itsMyLife = {
    name: 'It\'s my life',
    description: 'Everyday life from corners of the world.',
    icon: 'https://twimg0-a.akamaihd.net/profile_images/2371312033/image.jpg',
    iconThumbnail: 'https://twimg0-a.akamaihd.net/profile_images/2371312033/image.jpg',
    permission: 'public',
    type: 'post',
    category: 'life',
    _createdBy: 'aaronsw'
  };

  makingStuff = {
    name: 'Making Stuff',
    description: 'Everybody can make stuff. This is about stuff you\'ve made.',
    icon: 'http://cdnimg.visualizeus.com/thumbs/aa/06/colors,colours,costume,derro,fancy,dress,festival-aa06d899eec02dec6f84cb017ea3bf80_h.jpg',
    iconThumbnail: 'http://cdnimg.visualizeus.com/thumbs/aa/06/colors,colours,costume,derro,fancy,dress,festival-aa06d899eec02dec6f84cb017ea3bf80_h.jpg',
    permission: 'public',
    type: 'post',
    category: 'life',
    _createdBy: 'aaronsw'
  };

  travel = {
    name: 'Travel',
    description: 'Let\'s go.',
    icon: 'http://farm9.staticflickr.com/8511/8462042254_23a8ac6f5d_b.jpg',
    iconThumbnail: 'http://farm9.staticflickr.com/8511/8462042254_23a8ac6f5d_b.jpg',
    permission: 'public',
    type: 'post',
    category: 'travel',
    _createdBy: 'aaronsw'
  };

  computers = {
    name: 'Computers',
    description: 'Good world of pixels.',
    icon: 'http://images.apple.com/imac/images/hero.png',
    iconThumbnail: 'http://images.apple.com/imac/images/hero.png',
    permission: 'public',
    type: 'post',
    category: 'technology',
    _createdBy: 'aaronsw'
  };

  theGreatMasters = {
    name: 'Great Masters',
    description: 'Paintings from the great masters.',
    icon: 'http://images.apple.com/imac/images/hero.png',
    iconThumbnail: 'http://images.apple.com/imac/images/hero.png',
    permission: 'public',
    type: 'post',
    category: 'art',
    _createdBy: 'aaronsw'
  };

  streetFood = {
    name: 'Street Food',
    description: 'Dai Pai Dong to Vada Pav. The love of street food.',
    icon: 'http://shecookshecleans.files.wordpress.com/2011/07/korean-chic-skewers.jpg?w=500',
    iconThumbnail: 'http://shecookshecleans.files.wordpress.com/2011/07/korean-chic-skewers.jpg?w=500',
    permission: 'public',
    type: 'post',
    category: 'food-and-drinks',
    _createdBy: 'aaronsw'
  };

  guzzlers = {
    name: 'Guzzlers',
    description: 'Calling Beer guzzlers. We are already a few pitchers down.',
    icon: 'http://media.tumblr.com/tumblr_mdlnc6eBsm1qd0jy3.jpg',
    iconThumbnail: 'http://media.tumblr.com/tumblr_mdlnc6eBsm1qd0jy3.jpg',
    permission: 'public',
    type: 'post',
    category: 'food-and-drinks',
    _createdBy: 'aaronsw'
  };

  earlyMornings = {
    name: 'Early Mornings',
    description: 'Waking up early. Catching the day in its best act.',
    icon: 'http://www.minigallery.co.uk/Erica_Kirkpatrick/images/20120426093259079_l/large/Misty_Pond_Landscape_42.jpg',
    iconThumbnail: 'http://www.minigallery.co.uk/Erica_Kirkpatrick/images/20120426093259079_l/large/Misty_Pond_Landscape_42.jpg',
    permission: 'public',
    type: 'post',
    category: 'life',
    _createdBy: 'aaronsw'
  };

  forums = [poetry, movies, rawNerve, itsMyLife, makingStuff, travel, computers, theGreatMasters, streetFood, guzzlers, earlyMornings];

  believeYouCanChange = {
    title: 'Believe you can change',
    _content: 'believe-you-can-change.md',
    cover: 'http://3.bp.blogspot.com/-v3u0buEsK5E/T7XVL4nuUtI/AAAAAAAACu8/2Hte6GPRJ_M/s1600/dolphin.png',
    smallCover: 'http://3.bp.blogspot.com/-v3u0buEsK5E/T7XVL4nuUtI/AAAAAAAACu8/2Hte6GPRJ_M/s1600/dolphin.png',
    _forum: 'raw-nerve',
    _createdBy: 'aaronsw',
    _meta: 'featured'
  };

  cherishMistakes = {
    title: 'Cherish Mistakes',
    _content: 'cherish-mistakes.md',
    cover: 'http://img2.etsystatic.com/008/0/5851351/il_fullxfull.370263870_r8lg.jpg',
    smallCover: 'http://img2.etsystatic.com/008/0/5851351/il_fullxfull.370263870_r8lg.jpg',
    _forum: 'raw-nerve',
    _createdBy: 'aaronsw',
    _meta: 'featured'
  };

  confrontReality = {
    title: 'Confront Reality',
    _content: 'confront-reality.md',
    cover: 'http://www.cariboobrewing.com/wp-content/uploads/back-to-the-future-lloyd-michael-j-fox.jpeg',
    smallCover: 'http://www.cariboobrewing.com/wp-content/uploads/back-to-the-future-lloyd-michael-j-fox.jpeg',
    _forum: 'raw-nerve',
    _createdBy: 'aaronsw',
    _meta: 'featured'
  };

  darkKnight = {
    title: 'Dark Knight',
    _content: 'dark-knight.md',
    cover: 'http://www.geeksofdoom.com/GoD/img/2008/09/2008-09-11-dark_knight.jpg',
    smallCover: 'http://www.geeksofdoom.com/GoD/img/2008/09/2008-09-11-dark_knight.jpg',
    _forum: 'raw-nerve',
    _createdBy: 'aaronsw',
    _meta: 'featured'
  };

  fixTheMachine = {
    title: 'Lean into the pain',
    _content: 'lean-into-the-pain.md',
    cover: 'http://www.woodstock.com/images/spot1.jpg',
    smallCover: 'http://www.woodstock.com/images/spot1.jpg',
    _forum: 'raw-nerve',
    _createdBy: 'aaronsw',
    _meta: 'featured'
  };

  leanIntoThePain = {
    title: 'Fix the machine not the person',
    _content: 'fix-the-machine-not-the-person.md',
    cover: 'http://25.media.tumblr.com/tumblr_mdcyr848za1qgfiato1_1280.jpg',
    smallCover: 'http://25.media.tumblr.com/tumblr_mdcyr848za1qgfiato1_1280.jpg',
    _forum: 'raw-nerve',
    _createdBy: 'aaronsw',
    _meta: 'featured'
  };

  lookAtYourselfObjectively = {
    title: 'Look at yourself objectively',
    _content: 'look-at-yourself-objectively.md',
    _forum: 'raw-nerve',
    _createdBy: 'aaronsw',
    _meta: 'featured'
  };

  optimalBiases = {
    title: 'Optimal biases',
    _content: 'optimal-biases.md',
    cover: 'http://upload.wikimedia.org/wikipedia/commons/d/da/Claude_Monet,_Saint-Georges_majeur_au_cr%C3%A9puscule.jpg',
    smallCover: 'http://upload.wikimedia.org/wikipedia/commons/d/da/Claude_Monet,_Saint-Georges_majeur_au_cr%C3%A9puscule.jpg',
    _forum: 'raw-nerve',
    _createdBy: 'aaronsw',
    _meta: 'featured'
  };

  takeAStepBack = {
    title: 'Take a step back',
    _content: 'take-a-step-back.md',
    cover: 'http://thelittlecorporal.files.wordpress.com/2012/02/great_dictator.jpg',
    smallCover: 'http://thelittlecorporal.files.wordpress.com/2012/02/great_dictator.jpg',
    _forum: 'raw-nerve',
    _createdBy: 'aaronsw',
    _meta: 'featured'
  };

  articles = [believeYouCanChange, cherishMistakes, confrontReality, darkKnight, fixTheMachine, leanIntoThePain, lookAtYourselfObjectively, optimalBiases, takeAStepBack];

  exports.users = users;

  exports.forums = forums;

  exports.articles = articles;

}).call(this);
