// Generated by CoffeeScript 1.6.2
(function() {
  var HOST, PORT, async, conf, data, database, doHttpRequest, fs, http, init, path, querystring, utils,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  http = require('http');

  path = require('path');

  fs = require('fs');

  querystring = require('querystring');

  async = require('../../common/async');

  utils = require('../../common/utils');

  data = require('./data');

  conf = require('../../conf');

  database = new (require('../../common/database')).Database(conf.db);

  console.log("Setup started at " + (new Date));

  console.log("NODE_ENV is " + process.env.NODE_ENV);

  console.log("Setup will connect to database " + conf.db.name + " on " + conf.db.host);

  HOST = 'local.foraproject.org';

  PORT = '80';

  if (process.env.NODE_ENV !== 'development') {
    console.log('Setup can only be run in development.');
    process.exit();
  }

  if (HOST !== 'local.foraproject.org') {
    console.log('HOST should be local.');
    process.exit();
  }

  init = function() {
    var createForum, createForumTasks, createPost, createPostTasks, createUser, createUserTasks, forum, post, tasks, user, _fn, _fn1, _fn2, _globals, _i, _j, _k, _len, _len1, _len2, _ref, _ref1, _ref2;

    _globals = {};
    if (__indexOf.call(process.argv, '--delete') >= 0) {
      return database.getDb(function(err, db) {
        console.log('Deleting main database.');
        return db.dropDatabase(function(err, result) {
          console.log('Everything is gone now.');
          return process.exit();
        });
      });
    } else if (__indexOf.call(process.argv, '--create') >= 0) {
      console.log('This script will setup basic data. Calls the latest HTTP API.');
      _globals.sessions = {};
      createUser = function(user, cb) {
        console.log("Creating " + user.username + "...");
        user.secret = conf.networks[0].adminkeys["default"];
        return doHttpRequest('/api/v1/sessions', querystring.stringify(user), 'post', function(err, resp) {
          console.log("Created " + resp.username);
          _globals.sessions[user.username] = resp;
          return cb();
        });
      };
      createUserTasks = [];
      _ref = data.users;
      _fn = function(user) {
        return createUserTasks.push(function(cb) {
          return createUser(user, cb);
        });
      };
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        user = _ref[_i];
        _fn(user);
      }
      createForum = function(forum, cb) {
        var passkey;

        passkey = _globals.sessions[forum._createdBy].passkey;
        console.log("Creating a new forum with passkey(" + passkey + ")....");
        console.log("Creating " + forum.name + "...");
        delete forum._createdBy;
        return doHttpRequest("/api/v1/forums?passkey=" + passkey, querystring.stringify(forum), 'post', function(err, resp) {
          console.log("Created " + resp.name);
          return cb();
        });
      };
      createForumTasks = [];
      _ref1 = data.forums;
      _fn1 = function(forum) {
        return createForumTasks.push(function(cb) {
          return createForum(forum, cb);
        });
      };
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        forum = _ref1[_j];
        _fn1(forum);
      }
      createPost = function(post, cb) {
        var meta, passkey;

        passkey = _globals.sessions[post._createdBy].passkey;
        console.log("Creating a new post with passkey(" + passkey + ")....");
        console.log("Creating " + post.title + "...");
        post.content = fs.readFileSync(path.resolve(__dirname, "posts/" + post._content), 'utf-8');
        post.publish = true;
        forum = post._forum;
        meta = post._meta;
        delete post._forum;
        delete post._createdBy;
        delete post._content;
        delete post._meta;
        return doHttpRequest("/api/v1/" + forum + "?passkey=" + passkey, querystring.stringify(post), 'post', function(err, resp) {
          console.log("Created " + resp.title + " with uid " + resp.uid);
          if (meta.split(',').indexOf('featured') > -1) {
            return doHttpRequest("/api/v1/admin/feature?passkey=" + passkey + "&forum=" + resp.forums[0].stub + "&uid=" + resp.uid, null, 'get', function(err, r) {
              console.log("Added featured tag to post " + resp.title + ".");
              return cb();
            });
          }
        });
      };
      createPostTasks = [];
      _ref2 = data.posts;
      _fn2 = function(post) {
        return createPostTasks.push(function(cb) {
          return createPost(post, cb);
        });
      };
      for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
        post = _ref2[_k];
        _fn2(post);
      }
      tasks = function() {
        return async.series(createUserTasks, function() {
          console.log('Created users.');
          return async.series(createForumTasks, function() {
            console.log('Created forums.');
            return async.series(createPostTasks, function() {
              console.log('Created posts.');
              return console.log('Setup complete.');
            });
          });
        });
      };
      console.log('Setup will begin in 3 seconds.');
      return setTimeout(tasks, 1000);
    } else {
      console.log('Invalid option.');
      return process.exit();
    }
  };

  doHttpRequest = function(url, data, method, cb) {
    var options, req, response;

    options = {
      host: HOST,
      port: PORT,
      path: url,
      method: method,
      headers: data ? {
        'Content-Type': 'application/x-www-form-urlencoded',
        'Content-Length': data.length
      } : {
        'Content-Type': 'application/x-www-form-urlencoded',
        'Content-Length': 0
      }
    };
    response = '';
    req = http.request(options, function(res) {
      res.setEncoding('utf8');
      res.on('data', function(chunk) {
        return response += chunk;
      });
      return res.on('end', function() {
        return cb(null, JSON.parse(response));
      });
    });
    if (data) {
      req.write(data);
    }
    return req.end();
  };

  init();

}).call(this);
