// Generated by CoffeeScript 1.6.3
(function() {
  var AppError, Articles, conf, controller, db, models, utils, _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  controller = require('../controller');

  conf = require('../../../conf');

  db = new (require('../../../common/database')).Database(conf.db);

  models = require('../../../models');

  utils = require('../../../common/utils');

  AppError = require('../../../common/apperror').AppError;

  Articles = (function(_super) {
    __extends(Articles, _super);

    function Articles() {
      this.item = __bind(this.item, this);
      _ref = Articles.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Articles.prototype.item = function(req, res, next, article, forum) {
      article.formattedContent = article.formatContent();
      return res.render('articles/item.hbs', {
        article: article,
        pageName: 'article-page',
        pageType: 'std-page'
      });
    };

    return Articles;

  })(controller.Controller);

  exports.Articles = Articles;

}).call(this);
