// Generated by CoffeeScript 1.6.3
(function() {
  var AppError, Forums, conf, controller, db, models, utils,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  controller = require('../controller');

  conf = require('../../../conf');

  db = new (require('../../../common/database')).Database(conf.db);

  models = require('../../../models');

  utils = require('../../../common/utils');

  AppError = require('../../../common/apperror').AppError;

  Forums = (function(_super) {
    __extends(Forums, _super);

    function Forums() {
      this.forum = __bind(this.forum, this);
      this.index = __bind(this.index, this);
    }

    Forums.prototype.index = function(req, res, next) {
      var _this = this;
      return this.attachUser(arguments, function() {
        return models.Forum.find({
          network: req.network.stub
        }, (function(cursor) {
          return cursor.sort({
            lastPost: -1
          }).limit(12);
        }), {}, db, function(err, featured) {
          var forum, _i, _len;
          for (_i = 0, _len = featured.length; _i < _len; _i++) {
            forum = featured[_i];
            forum.summary = forum.getView("card");
            forum.summary.view = "standard";
          }
          return res.render('forums/index.hbs', {
            featured: featured,
            pageName: 'forums-page',
            pageType: 'cover-page',
            cover: '/pub/images/cover.jpg'
          });
        });
      });
    };

    Forums.prototype.forum = function(req, res, next) {
      var _this = this;
      return this.attachUser(arguments, function() {
        return res.render('forums/index.hbs', {
          editorsChoices: editorsChoices,
          featured: featured,
          pageName: 'home-page',
          pageType: 'cover-page',
          cover: 'http://blogs-images.forbes.com/singularity/files/2013/01/Aaron_Swartz.jpg'
        });
      });
    };

    return Forums;

  })(controller.Controller);

  exports.Forums = Forums;

}).call(this);
