// Generated by CoffeeScript 1.6.3
(function() {
  var AppError, Home, conf, controller, db, models, utils,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  controller = require('../controller');

  conf = require('../../../conf');

  db = new (require('../../../common/database')).Database(conf.db);

  models = require('../../../models');

  utils = require('../../../common/utils');

  AppError = require('../../../common/apperror').AppError;

  Home = (function(_super) {
    __extends(Home, _super);

    function Home() {
      this.index = __bind(this.index, this);
    }

    Home.prototype.index = function(req, res, next) {
      var _this = this;
      return this.attachUser(arguments, function() {
        return models.Post.find({
          meta: 'pick',
          'forum.network': req.network.stub
        }, (function(cursor) {
          return cursor.sort({
            _id: -1
          }).limit(1);
        }), {}, db, function(err, editorsPicks) {
          var post, _i, _len;
          for (_i = 0, _len = editorsPicks.length; _i < _len; _i++) {
            post = editorsPicks[_i];
            post.summary = post.getView("card");
            post.summary.view = "wide";
          }
          return models.Post.find({
            meta: 'featured',
            'forum.network': req.network.stub
          }, (function(cursor) {
            return cursor.sort({
              _id: -1
            }).limit(12);
          }), {}, db, function(err, featured) {
            var f, x, _j, _len1;
            featured = (function() {
              var _j, _len1, _results;
              _results = [];
              for (_j = 0, _len1 = featured.length; _j < _len1; _j++) {
                f = featured[_j];
                if (((function() {
                  var _k, _len2, _results1;
                  _results1 = [];
                  for (_k = 0, _len2 = editorsPicks.length; _k < _len2; _k++) {
                    x = editorsPicks[_k];
                    _results1.push(x._id);
                  }
                  return _results1;
                })()).indexOf(f._id) === -1) {
                  _results.push(f);
                }
              }
              return _results;
            })();
            for (_j = 0, _len1 = featured.length; _j < _len1; _j++) {
              post = featured[_j];
              post.summary = post.getView("card");
              post.summary.view = "standard";
            }
            return res.render('home/index.hbs', {
              editorsPicks: editorsPicks,
              featured: featured,
              pageName: 'home-page',
              pageType: 'cover-page',
              cover: '/pub/images/cover.jpg'
            });
          });
        });
      });
    };

    return Home;

  })(controller.Controller);

  exports.Home = Home;

}).call(this);
